/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.EquipoQueNoAceptaMasIntegrantes.Vista;

import com.EquipoQueNoAceptaMasIntegrantes.Controladores.ControladorIdioma;
import com.EquipoQueNoAceptaMasIntegrantes.Controladores.ControladorInicio;
import com.EquipoQueNoAceptaMasIntegrantes.Modelo.objetos.Oferta;
import lombok.Getter;

import javax.swing.*;
import java.awt.event.ActionListener;
import java.util.List;
import java.util.stream.Collectors;

@Getter

/**
 *
 * @author Jose
 */
public class VistaOfertas extends javax.swing.JFrame {

    /**
     * Creates new form VistaOfertas
     */
    public VistaOfertas() {
        initComponents();
    }

    public void addActionListenerEspecifico(JButton boton, ActionListener accion){
        boton.addActionListener(accion);
    }

    public void imprimirOfertas(){
        List<Oferta> ofertas=(List<Oferta>) ControladorInicio.repositorioOferta.findAll();
        if (ofertas.isEmpty()) {
            labelOfertas.setText(ControladorIdioma.msg.getProperty("msg.sinOfertas"));
         //   System.out.println(ControladorIdioma.msg.getProperty("msg.sinOfertas"));
        } else {
            String ofertasString=ofertas.stream().map(Oferta::toString).collect(Collectors.joining("<p>"));
            labelOfertas.setText(ofertasString);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelOfertas = new javax.swing.JLabel();
        botonRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelOfertas.setText("aqui se muestran las ofertas");
        jPanel1.add(labelOfertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 870, 370));

        botonRegresar.setText("regresar ");
        jPanel1.add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 160, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 897, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelOfertas;
    // End of variables declaration//GEN-END:variables
}
