/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.EquipoQueNoAceptaMasIntegrantes.Vista;

import com.EquipoQueNoAceptaMasIntegrantes.Controladores.ControladorIdioma;

import java.awt.event.ActionListener;

/**
 *
 * @author Jose
 */
public class VistaDecoraciones extends javax.swing.JFrame {

    /**
     * Creates new form VistaDecoraciones
     */
    public VistaDecoraciones() {
        initComponents();
        ///cambiar en la version final, el ide lo cambia si lo ejecuto, mejor cambiarlo al final
        botonCena.setText(ControladorIdioma.msg.getProperty("msg.Cena"));
        botonChampagne.setText(ControladorIdioma.msg.getProperty("msg.Champagne"));
        botonChocolates.setText(ControladorIdioma.msg.getProperty("msg.Chocolates"));
        botonFlores.setText(ControladorIdioma.msg.getProperty("msg.Flores"));
    }
    public void setText(String cadena){
        labelResumenHabitacion.setText(cadena);
    }
    public void addActionListener(ActionListener controladorDecoraciones) {
        botonCena.addActionListener(controladorDecoraciones);
        botonChampagne.addActionListener(controladorDecoraciones);
        botonChocolates.addActionListener(controladorDecoraciones);
        botonFlores.addActionListener(controladorDecoraciones);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonCena = new javax.swing.JButton();
        botonChampagne = new javax.swing.JButton();
        botonChocolates = new javax.swing.JButton();
        botonFlores = new javax.swing.JButton();
        labelResumenHabitacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonCena.setText("Cena");
        botonCena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCenaActionPerformed(evt);
            }
        });
        jPanel1.add(botonCena, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 190, 40));

        botonChampagne.setText("Champagne");
        jPanel1.add(botonChampagne, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 190, 40));

        botonChocolates.setText("Chocolates");
        jPanel1.add(botonChocolates, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 190, 40));

        botonFlores.setText("Flores");
        botonFlores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFloresActionPerformed(evt);
            }
        });
        jPanel1.add(botonFlores, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 190, 50));

        labelResumenHabitacion.setText("resumenHabitacion");
        jPanel1.add(labelResumenHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 450, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCenaActionPerformed

    private void botonFloresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFloresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonFloresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCena;
    private javax.swing.JButton botonChampagne;
    private javax.swing.JButton botonChocolates;
    private javax.swing.JButton botonFlores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelResumenHabitacion;
    // End of variables declaration//GEN-END:variables
}
