/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.EquipoQueNoAceptaMasIntegrantes.Vista;

import com.EquipoQueNoAceptaMasIntegrantes.Controladores.ControladorIdioma;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;

/**
 *
 * @author Jose
 */
public class VistaIdioma extends javax.swing.JFrame {

    /**
     * Creates new form vistaIdioma
     */
    public VistaIdioma() {
        initComponents();
        escalarImagenAlLabel(logo, "/images/Logo.png");
    }
    public void addActionListener(ActionListener controladorIdioma) {
        botonEnglish.addActionListener(controladorIdioma);
        botonEspanol.addActionListener(controladorIdioma);
        botonPortuguese.addActionListener(controladorIdioma);
    }
    private void escalarImagenAlLabel(JLabel labelname, String root){
        ImageIcon image = new javax.swing.ImageIcon(getClass().getResource(root));
        labelname.setIcon(new ImageIcon(image.getImage().getScaledInstance(labelname.getWidth(),labelname.getHeight(), Image.SCALE_DEFAULT)));

    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imagenHotel = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        textoSeleccionarIdioma = new javax.swing.JLabel();
        botonPortuguese = new javax.swing.JButton();
        botonEnglish = new javax.swing.JButton();
        botonEspanol = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagenHotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagenEnIdiomaFinal.jpg"))); // NOI18N
        jPanel1.add(imagenHotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 390, 720));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 160, 160));

        textoSeleccionarIdioma.setBackground(new java.awt.Color(255, 255, 255));
        textoSeleccionarIdioma.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        textoSeleccionarIdioma.setText("Choose your Language ");
        jPanel1.add(textoSeleccionarIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, -1));

        botonPortuguese.setText("Portuguese");
        jPanel1.add(botonPortuguese, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, 210, 70));

        botonEnglish.setText("English");
        botonEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnglishActionPerformed(evt);
            }
        });
        jPanel1.add(botonEnglish, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 210, 70));

        botonEspanol.setText("Espanol");
        jPanel1.add(botonEspanol, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 210, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnglishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEnglishActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEnglish;
    private javax.swing.JButton botonEspanol;
    private javax.swing.JButton botonPortuguese;
    private javax.swing.JLabel imagenHotel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel textoSeleccionarIdioma;
    // End of variables declaration//GEN-END:variables
}
