/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.EquipoQueNoAceptaMasIntegrantes.Vista;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;

/**
 *
 * @author Jose
 */
public class VistaHabitaciones extends javax.swing.JFrame {

    /**
     * Creates new form VistaHabitaciones
     */
    public VistaHabitaciones() {
        initComponents();
        numPeopleText.setVisible(false);
        campoNumHabitacion.setVisible(false);
        botonConfirmarHabitacion.setVisible(false);

    }
    private void setVisible(JComponent panel){
        panel.setVisible(true);
    }
    public void activarBotones(){
        setVisible(numPeopleText);
        setVisible(campoNumHabitacion);
        setVisible(botonConfirmarHabitacion);
    }


    public int getPersonas(){
        int personas=0;
        try{
            personas=Integer.parseInt(campoTextoPersonas.getText());
        }catch (NumberFormatException e){
            labelCachadorDeErrores.setText("Ingresa un numero valido");
        }
        return personas;
    }
    public int getNoches(){
        int noches=0;
        try{
            noches=Integer.parseInt(campoTextoNoches.getText());
        }catch (NumberFormatException e){
            labelCachadorDeErrores.setText("Ingresa un numero valido");
        }
        return noches;
    }
    public void addActionListener(ActionListener controladorHabitaciones) {
        botonConfirmar.addActionListener(controladorHabitaciones);
        botonConfirmarHabitacion.addActionListener(controladorHabitaciones);
    }
    public void setTextHabitaciones(String cadena){
        loQueDebeAparecer.setText(cadena);
    }
    public void setTextError(String cadena){
        labelCachadorDeErrores.setText(cadena);
    }
    public void setTextErrorNumHab(String cadena){
        labelErrorNumHab.setText(cadena);
    }
    public int getNumHabitacion(){
        int numero=0;
        try{
            numero=Integer.parseInt(campoNumHabitacion.getText());
        }catch (NumberFormatException e){
            labelErrorNumHab.setText("Ingresa un numero valido");
        }

        return numero;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        numPeopleText = new javax.swing.JLabel();
        campoTextoPersonas = new javax.swing.JTextField();
        campoTextoNoches = new javax.swing.JTextField();
        textoNumNoches = new javax.swing.JLabel();
        botonConfirmar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        botonConfirmarHabitacion = new javax.swing.JButton();
        campoNumHabitacion = new javax.swing.JTextField();
        textoNumPersonas1 = new javax.swing.JLabel();
        labelCachadorDeErrores = new javax.swing.JLabel();
        loQueDebeAparecer = new javax.swing.JLabel();
        labelErrorNumHab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setPreferredSize(new java.awt.Dimension(900, 720));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numPeopleText.setText("Ingresa el numero de habitacion que quieres apartar y presiona el boton");
        panel.add(numPeopleText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 490, 50));
        panel.add(campoTextoPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 130, 50));
        panel.add(campoTextoNoches, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 130, 50));

        textoNumNoches.setText("Numero de noches");
        panel.add(textoNumNoches, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 170, 50));

        botonConfirmar.setText("Confirmar");
        botonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmarActionPerformed(evt);
            }
        });
        panel.add(botonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 130, 50));

        jPanel1.setBackground(new java.awt.Color(255, 51, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        jPanel3.setBackground(new java.awt.Color(51, 255, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, -1, -1));

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 580, -1, -1));

        botonConfirmarHabitacion.setText("Confirmar Habitacion");
        botonConfirmarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmarHabitacionActionPerformed(evt);
            }
        });
        panel.add(botonConfirmarHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 200, 70));

        campoNumHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumHabitacionActionPerformed(evt);
            }
        });
        panel.add(campoNumHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 170, 50));

        textoNumPersonas1.setText("Numero de Personas");
        panel.add(textoNumPersonas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 170, 50));
        panel.add(labelCachadorDeErrores, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 290, 30));
        panel.add(loQueDebeAparecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 700, 570));
        panel.add(labelErrorNumHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 230, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonConfirmarActionPerformed

    private void botonConfirmarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarHabitacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonConfirmarHabitacionActionPerformed

    private void campoNumHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumHabitacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumHabitacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConfirmar;
    private javax.swing.JButton botonConfirmarHabitacion;
    private javax.swing.JTextField campoNumHabitacion;
    private javax.swing.JTextField campoTextoNoches;
    private javax.swing.JTextField campoTextoPersonas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelCachadorDeErrores;
    private javax.swing.JLabel labelErrorNumHab;
    private javax.swing.JLabel loQueDebeAparecer;
    private javax.swing.JLabel numPeopleText;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel textoNumNoches;
    private javax.swing.JLabel textoNumPersonas1;
    // End of variables declaration//GEN-END:variables
}
