/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.EquipoQueNoAceptaMasIntegrantes.Vista;

import com.EquipoQueNoAceptaMasIntegrantes.Controladores.ControladorIdioma;
import lombok.Getter;
import lombok.Setter;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
@Getter
@Setter

/**
 *
 * @author Jose
 */
public class VistaDecoraciones extends javax.swing.JFrame {

    /**
     * Creates new form VistaDecoraciones
     */
    public VistaDecoraciones() {
        initComponents();
        ///cambiar en la version final, el ide lo cambia si lo ejecuto, mejor cambiarlo al final
        botonCena.setText(ControladorIdioma.msg.getProperty("msg.Cena"));
        botonChampagne.setText(ControladorIdioma.msg.getProperty("msg.Champagne"));
        botonChocolates.setText(ControladorIdioma.msg.getProperty("msg.Chocolates"));
        botonFlores.setText(ControladorIdioma.msg.getProperty("msg.Flores"));
        cantidadCena.setName("Cena");
        cantidadChampagne.setName("Champagne");
        cantidadChocolates.setName("Chocolates");
        cantidadFLores.setName("Flores");

    }
    
    public void setText(String cadena){
        labelResumenHabitacion.setText(cadena);
    }
    public void setTextConfirmacion(String cadena){
        msgPreparando.setText(cadena);
    }
    public void setTextMsgDecoraciones(String cadena){
        msgDecoradores.setText(cadena);

    }
    public int getCantidadDecoraciones(JLabel label){
        int cantidad=0;
        try{
            cantidad = Integer.parseInt(label.getText());
        }catch (NumberFormatException e){
            //Esto no va a pasar
        }

        return cantidad;
    }
    public void setTextoLabel(JLabel label,String cadena){
        label.setText(cadena);
    }

    public void addActionListenerEspecifico(JButton boton, ActionListener accion){
        boton.addActionListener(accion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonCena = new javax.swing.JButton();
        botonChampagne = new javax.swing.JButton();
        botonChocolates = new javax.swing.JButton();
        botonFlores = new javax.swing.JButton();
        labelResumenHabitacion = new javax.swing.JLabel();
        msgPreparando = new javax.swing.JLabel();
        cantidadCena = new javax.swing.JLabel();
        cantidadChampagne = new javax.swing.JLabel();
        cantidadChocolates = new javax.swing.JLabel();
        cantidadFLores = new javax.swing.JLabel();
        msgDecoradores = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        botonContinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonCena.setText("Cena");
        botonCena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCenaActionPerformed(evt);
            }
        });
        jPanel1.add(botonCena, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 190, 40));

        botonChampagne.setText("Champagne");
        jPanel1.add(botonChampagne, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 190, 40));

        botonChocolates.setText("Chocolates");
        jPanel1.add(botonChocolates, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 190, 40));

        botonFlores.setText("Flores");
        botonFlores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFloresActionPerformed(evt);
            }
        });
        jPanel1.add(botonFlores, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 190, 50));

        labelResumenHabitacion.setText("resumenHabitacion");
        jPanel1.add(labelResumenHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 300, 200));
        jPanel1.add(msgPreparando, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 270, 70));
        jPanel1.add(cantidadCena, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 120, 50));
        jPanel1.add(cantidadChampagne, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 120, 50));
        jPanel1.add(cantidadChocolates, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 120, 50));
        jPanel1.add(cantidadFLores, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, 120, 50));
        jPanel1.add(msgDecoradores, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 270, 70));

        jLabel1.setText("Cantidad:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 80, 30));

        botonContinuar.setText("Continuar");
        botonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonContinuarActionPerformed(evt);
            }
        });
        jPanel1.add(botonContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 610, 190, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCenaActionPerformed

    private void botonFloresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFloresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonFloresActionPerformed

    private void botonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonContinuarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonContinuarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCena;
    private javax.swing.JButton botonChampagne;
    private javax.swing.JButton botonChocolates;
    private javax.swing.JButton botonContinuar;
    private javax.swing.JButton botonFlores;
    private javax.swing.JLabel cantidadCena;
    private javax.swing.JLabel cantidadChampagne;
    private javax.swing.JLabel cantidadChocolates;
    private javax.swing.JLabel cantidadFLores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelResumenHabitacion;
    private javax.swing.JLabel msgDecoradores;
    private javax.swing.JLabel msgPreparando;
    // End of variables declaration//GEN-END:variables
}
